import {beforeEach,expect,it,vi} from 'vitest';
import {Account,Keypair,Networks,StrKey,nativeToScVal,TransactionBuilder,BASE_FEE,Contract} from '@stellar/stellar-sdk';
import {makeClient} from './contract';
const mocks=vi.hoisted(()=>({getNetwork:vi.fn(),getAccount:vi.fn(),simulateTransaction:vi.fn(),sendTransaction:vi.fn(),pollTransaction:vi.fn()}));
vi.mock('@stellar/stellar-sdk',async importOriginal=>{const actual=await importOriginal<typeof import('@stellar/stellar-sdk')>();return {...actual,rpc:{...actual.rpc,Server:class {getNetwork=mocks.getNetwork;getAccount=mocks.getAccount;simulateTransaction=mocks.simulateTransaction;sendTransaction=mocks.sendTransaction;pollTransaction=mocks.pollTransaction;}}};});
const source=Keypair.random().publicKey();
const config={network:'testnet' as const,passphrase:Networks.TESTNET,rpcUrl:'https://soroban-testnet.stellar.org',contractId:StrKey.encodeContract(Buffer.alloc(32,3)),explorerBaseUrl:'https://stellar.expert/explorer/testnet'};
beforeEach(()=>{vi.clearAllMocks();mocks.getNetwork.mockResolvedValue({passphrase:Networks.TESTNET});mocks.getAccount.mockResolvedValue(new Account(source,'1'));});
it('rejects a mainnet RPC before reading accounts or simulating',async()=>{mocks.getNetwork.mockResolvedValue({passphrase:Networks.PUBLIC});await expect(makeClient(config).read(source,'get_group',[])).rejects.toThrow('not Stellar testnet');expect(mocks.getAccount).not.toHaveBeenCalled();expect(mocks.simulateTransaction).not.toHaveBeenCalled();});
it('surfaces contract simulation failures without attempting submission',async()=>{mocks.simulateTransaction.mockResolvedValue({error:'Error(Contract, #1)',events:[],latestLedger:1});await expect(makeClient(config).read(source,'get_group',[])).rejects.toThrow('Error(Contract, #1)');expect(mocks.sendTransaction).not.toHaveBeenCalled();});
it('returns the real simulated value for public reads without signing',async()=>{const retval=nativeToScVal(3n,{type:'u64'});mocks.simulateTransaction.mockResolvedValue({id:'test',latestLedger:1,events:[],transactionData:{},minResourceFee:'0',result:{auth:[],retval}});expect(await makeClient(config).read(source,'get_group',[])).toBe(retval);expect(mocks.sendTransaction).not.toHaveBeenCalled();});
it('rejects an incomplete simulation response',async()=>{mocks.simulateTransaction.mockResolvedValue({id:'test',latestLedger:1,events:[]});await expect(makeClient(config).read(source,'get_group',[])).rejects.toThrow();});
function submitted(){return new TransactionBuilder(new Account(source,'1'),{fee:BASE_FEE,networkPassphrase:Networks.TESTNET}).addOperation(new Contract(config.contractId).call('execute',nativeToScVal(1n,{type:'u64'}))).setTimeout(60).build();}
const txHash=(tx:ReturnType<typeof submitted>)=>Array.from(tx.hash(),byte=>byte.toString(16).padStart(2,'0')).join('');
it('keeps the deterministic transaction hash after an ambiguous send failure and never retries',async()=>{const tx=submitted();mocks.sendTransaction.mockRejectedValue(new Error('connection dropped'));await expect(makeClient(config).submit(tx.toXDR())).rejects.toThrow(txHash(tx));expect(mocks.sendTransaction).toHaveBeenCalledTimes(1);expect(mocks.pollTransaction).not.toHaveBeenCalled();});
it('keeps the transaction hash when confirmation fails',async()=>{const tx=submitted();mocks.sendTransaction.mockResolvedValue({status:'PENDING',hash:txHash(tx)});mocks.pollTransaction.mockRejectedValue(new Error('timeout'));await expect(makeClient(config).submit(tx.toXDR())).rejects.toThrow(txHash(tx));expect(mocks.sendTransaction).toHaveBeenCalledTimes(1);});
it('exposes a structured hash on ambiguous submission errors',async()=>{const tx=submitted();mocks.sendTransaction.mockRejectedValue(new Error('connection dropped'));await expect(makeClient(config).submit(tx.toXDR())).rejects.toMatchObject({name:'TransactionOutcomeError',hash:txHash(tx)});});
it('rechecks RPC network immediately before submission and refuses a mismatch',async()=>{mocks.getNetwork.mockResolvedValue({passphrase:Networks.PUBLIC});await expect(makeClient(config).submit(submitted().toXDR())).rejects.toThrow('changed away from Stellar testnet');expect(mocks.sendTransaction).not.toHaveBeenCalled();});
it('does not send after action cancellation during network verification',async()=>{await expect(makeClient(config).submit(submitted().toXDR(),()=>false)).rejects.toThrow('cancelled before submission');expect(mocks.sendTransaction).not.toHaveBeenCalled();});
