import {useEffect,useRef,useState,type FormEvent} from 'react';
import {scValToNative} from '@stellar/stellar-sdk';
import {Field} from '../components/Field';
import {GroupSummary} from '../components/GroupSummary';
import {resolveNetworkConfig} from '../lib/network';
import {makeClient,TransactionOutcomeError} from '../lib/contract';
import {account,address,createGroupArgs,decode,hash,i128,list,positive,printable,u64,MAX_U64} from '../lib/treasury';
import {describeError} from '../lib/errors';
import {connectWallet,disconnectWallet,checkWalletNetwork,signWithWallet,rememberedAddress} from '../lib/wallet';
const configuration=resolveNetworkConfig({network:import.meta.env.VITE_STELLAR_NETWORK,rpcUrl:import.meta.env.VITE_SOROBAN_RPC_URL,contractId:import.meta.env.VITE_CONTRACT_ID,explorerBaseUrl:import.meta.env.VITE_EXPLORER_BASE_URL});
export function App(){
 const [wallet,setWallet]=useState(''),[source,setSource]=useState(''),[groupId,setGroupId]=useState(''),[proposalId,setProposalId]=useState('');
 const [group,setGroup]=useState<Record<string,unknown>|null>(null),[proposal,setProposal]=useState<Record<string,unknown>|null>(null),[member,setMember]=useState<Record<string,unknown>|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<{hash:string;value?:unknown}|null>(null),[uncertain,setUncertain]=useState<string|null>(null);
 const active=useRef(true),generation=useRef(0),inFlight=useRef(false);
 useEffect(()=>{active.current=true;return()=>{active.current=false;generation.current++;};},[]);
 async function run(action:()=>Promise<void>){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');const current=generation.current;try{await action();}catch(reason){if(active.current&&current===generation.current){setError(describeError(reason));if(reason instanceof TransactionOutcomeError)setUncertain(reason.hash);}}finally{inFlight.current=false;if(active.current&&current===generation.current)setBusy(false);}}
 const config=configuration.ok?configuration.config:null;
 const client=config?makeClient(config):null;
 const readSource=()=>account(wallet||source);
 async function write(method:string,args:Parameters<NonNullable<typeof client>['prepare']>[2]){
  if(!client||!config||!wallet)throw new Error('Connect a testnet wallet first.');
  const source=wallet,current=generation.current;
  const isCurrent=()=>active.current&&generation.current===current;
  if(!(await checkWalletNetwork()).onTestnet)throw new Error('Switch your wallet to Stellar testnet.');
  if(await rememberedAddress()!==source)throw new Error('The wallet account changed. Reconnect before preparing a transaction.');
  if(!isCurrent())return;
  const unsigned=await client.prepare(source,method,args);
  if(!isCurrent())return;
  const signed=await signWithWallet(unsigned,source,config.passphrase);
  if(!isCurrent())return;
  if(!(await checkWalletNetwork()).onTestnet)throw new Error('The wallet network changed. Switch to testnet.');
  if(await rememberedAddress()!==source)throw new Error('The wallet account changed while signing. No transaction was submitted.');
  if(!isCurrent())return;
  const result=await client.submit(signed,isCurrent);
  if(isCurrent()){setReceipt({hash:result.hash,value:result.value?scValToNative(result.value):undefined});setGroup(null);setProposal(null);setMember(null);}
 }
 const submit=(fn:(data:FormData)=>Promise<void>)=>(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);void run(()=>fn(data));};
 const value=(data:FormData,name:string)=>String(data.get(name)??'');
 const groupKey=()=>positive(groupId,MAX_U64),proposalKey=()=>positive(proposalId,MAX_U64);
 return <><div className="banner">TESTNET — no real money</div><header><p className="eyebrow">DUES • APPROVALS • ACCOUNTABILITY</p><h1>Your group’s treasury,<br/>with shared control.</h1><p>Members pay once per period. Signers approve spending. Every group keeps its own balance.</p><p className="warning">Custody prototype. Not independently reviewed. Deployment and funded testing remain blocked until a second human review.</p><button disabled={busy||!config} onClick={()=>void run(async()=>{const current=generation.current;if(wallet){await disconnectWallet();if(active.current&&current===generation.current){generation.current++;setWallet('');setBusy(false);setGroup(null);setProposal(null);setMember(null);}}else{const next=account(await connectWallet());if(!(await checkWalletNetwork()).onTestnet)throw new Error('Switch your wallet to testnet before connecting.');if(active.current&&current===generation.current){setWallet(next);setSource(next);}}})}>{wallet?'Disconnect wallet':'Connect testnet wallet'}</button>{wallet&&<p className="address">Connected: {wallet}</p>}</header><main>
 {!configuration.ok&&<section><h2>Configuration required</h2><p>The app will not operate until a reviewed testnet contract is configured.</p><ul>{configuration.problems.map(problem=><li key={problem}>{problem}</li>)}</ul></section>}
 {error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">Working… keep this page open.</p>}
 {uncertain&&config&&<section aria-label="Transaction needs review"><h2>Check the transaction outcome</h2><p>This transaction has not been confirmed by the app. Check it before repeating the action.</p><p className="address">{uncertain}</p><a href={`${config.explorerBaseUrl}/tx/${uncertain}`} target="_blank" rel="noreferrer">Check transaction on Stellar Explorer</a></section>}{receipt&&<section aria-label="Last successful transaction"><h2>Transaction confirmed</h2><p className="address">{receipt.hash}</p>{config&&<a href={`${config.explorerBaseUrl}/tx/${receipt.hash}`} target="_blank" rel="noreferrer">View on Stellar Explorer</a>}{receipt.value!==undefined&&<pre>Returned value: {printable(receipt.value)}</pre>}</section>}
 <fieldset disabled={busy||!config}><legend>Public group view</legend><p>No signing needed. A funded public testnet account is required as the simulation source; its secret is never needed.</p><Field disabled={busy} label="Public read source (G…); optional when connected" name="source" required={false} value={source} onChange={setSource}/><Field disabled={busy} label="Group ID" name="groupId" value={groupId} onChange={next=>{setGroupId(next);setGroup(null);setMember(null);}}/><button onClick={()=>void run(async()=>{setGroup(null);const data=decode(await client!.read(readSource(),'get_group',[u64(groupKey())]));if(active.current)setGroup(data);})}>Read group and balance</button>{group&&<><GroupSummary group={group}/><details><summary>Inspect the full group record</summary><pre>{printable(group)}</pre></details></>}<Field disabled={busy} label="Proposal ID" name="proposalId" value={proposalId} onChange={next=>{setProposalId(next);setProposal(null);}}/><button onClick={()=>void run(async()=>{setProposal(null);const data=decode(await client!.read(readSource(),'get_proposal',[u64(proposalKey())]));if(active.current)setProposal(data);})}>Read proposal and approvals</button>{proposal&&<pre>{printable(proposal)}</pre>}<p>Look up proposal IDs from creation receipts. v0 has no proposal index or historical event export.</p></fieldset>
 <div className="grid"><section><h2>For members</h2><form onSubmit={submit(async data=>{setMember(null);const record=decode(await client!.read(readSource(),'member_status',[u64(groupKey()),address(account(value(data,'member')))]));if(active.current)setMember(record);})}><Field disabled={busy} label="Member public address" name="member" onChange={()=>setMember(null)}/><button disabled={busy||!config}>Check current period dues</button></form>{member&&<pre>{printable(member)}</pre>}<button disabled={busy||!wallet||!config} onClick={()=>void run(()=>write('pay_dues',[u64(groupKey()),address(wallet)]))}>Pay current period dues</button><p>The group determines the amount and token. Inspect its record before approving the wallet request.</p></section>
 <section><h2>For signers</h2><form onSubmit={submit(data=>write('propose',[u64(groupKey()),address(wallet),address(account(value(data,'recipient'))),i128(positive(value(data,'amount'))),hash(value(data,'memo'))]))}><Field disabled={busy} label="Recipient public address" name="recipient"/><Field disabled={busy} label="Spend amount (token atomic units)" name="amount"/><Field disabled={busy} label="Off-chain description SHA-256 hash" name="memo"/><button disabled={busy||!wallet||!config}>Create spending proposal</button></form><button disabled={busy||!wallet||!config} onClick={()=>void run(()=>write('approve',[u64(proposalKey()),address(wallet)]))}>Approve selected proposal</button><button disabled={busy||!wallet||!config} onClick={()=>void run(()=>write('execute',[u64(proposalKey())]))}>Execute approved proposal</button><button disabled={busy||!wallet||!config} onClick={()=>void run(()=>write('cancel',[u64(proposalKey()),list([wallet])]))}>Cancel as proposer</button><p>Review the proposal before signing. Execution requires sufficient group balance and approvals. Threshold cancellation requires multiple authorizations; use the reviewed contract tooling for that flow.</p></section></div>
 <section><h2>Create a group</h2><form onSubmit={submit(data=>write('create_group',createGroupArgs(wallet,{token:value(data,'token'),members:value(data,'members'),signers:value(data,'signers'),threshold:value(data,'threshold'),dues:value(data,'dues'),period:value(data,'period')})))}><fieldset disabled={busy||!wallet||!config}><legend>Fixed governance settings</legend><Field disabled={busy} label="Token contract address" name="token"/><Field disabled={busy} label="Member addresses (comma or space separated, maximum 100)" name="members" textarea/><Field disabled={busy} label="Signer addresses (maximum 20)" name="signers" textarea/><Field disabled={busy} label="Required signer approvals" name="threshold"/><Field disabled={busy} label="Dues amount (token atomic units)" name="dues"/><Field disabled={busy} label="Period length in seconds (maximum 31,622,400)" name="period"/><button>Create group</button></fieldset></form><p>Membership and signer settings cannot be changed in v0. No organization names, contacts, or identity numbers belong on-chain.</p></section>
 </main><footer>Local v0 · No deployment or pilot claimed · <a href="https://github.com/stellar-duestreasury/duestreasury-docs">Documentation and limitations</a></footer></>;
}
